### ISSUE TITLE
About :how  to   get  the  keyboard input  value 

### ISSUE THREAD

**Issue by AmberWhiteSky** [Jungerr/GridPasswordView#3]
thanks,i have  get  the  password
very thanks you  open project.
i'm a  chinese developer
if haven't  you project  
my work  will become diffcult.
after i  will study you  project very careful.
very thansks

**Comment by Jungerr** [comment]
Well, could you tell me what app you are developing that use this library ? Thanks.

**Comment by Jungerr** [comment]
Well, i wonder which app you are developing that use my library ? Thanks a lot.
