### ISSUE TITLE
how to open soft keyboard automatically？

### ISSUE THREAD

**Issue by simplethink** [Jungerr/GridPasswordView#4]
I've tried 

InputMethodManager inputManager = (InputMethodManager) getContext().getSystemService(Context.INPUT_METHOD_SERVICE);
inputManager.showSoftInput(pswView, InputMethodManager.SHOW_IMPLICIT);

it didn't work.

thank you all the same.

**Comment by Richard-Cao** [comment]
android:windowSoftInputMode="adjustResize"
in AndroidManifest.xml
Thx

**Comment by simplethink** [comment]
It's my mistake.I put another unneeded edittext in layout view,it produces the soft keyboard type that it is not what i want.
Thx
